# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleCocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleCocoapods
    pod 'Alamofire','4.9.1'

  target 'SampleCocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
